# Changes here will be overwritten by Copier
_commit: 1.2.6
_src_path: gh:pawamoy/copier-pdm
author_email: pawamoy@pm.me
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2020'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
insiders: false
project_description: Load Python objects documentation.
project_name: pytkdocs
python_package_command_line_name: pytkdocs
python_package_distribution_name: pytkdocs
python_package_import_name: pytkdocs
repository_name: pytkdocs
repository_namespace: pawamoy
repository_provider: github.com

